version: '3.7'

networks:
  whisper_backend:
    external: true
  traefik_net:
    external: true

services:
  touchpoint-telegram:
    build: .
    container_name: touchpoint-telegram

    networks:
      - whisper_backend
      - traefik_net

    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHISPER_API_TOKEN=${WHISPER_API_TOKEN}
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}

    labels:
      - "traefik.enable=true"
      - traefik.http.routers.touchpoint-telegram.rule=(Host(`touchpoints.eventwhisper.de`)  && Path("/telegram{regex:$$|/.*}"))
      - "traefik.http.routers.touchpoint-telegram.entrypoints=websecure"
      - "traefik.http.routers.touchpoint-telegram.tls.certresolver=le"
      - "traefik.http.routers.touchpoint-telegram.tls=true"
      - "traefik.http.routers.touchpoint-telegram.service=touchpoint-telegram"
      - "traefik.http.services.touchpoint-telegram.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"
