name: Build and Deploy TouchpointTelegram
run-name: Build and Deploy TouchpointTelegram
on:
  push:
    paths:
      - touchpoints/telegram-2/**
      - .github/workflows/build-and-deploy-touchpoint-telegram.yml

jobs:
  BuildTouchpointTelegramDocker:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose -f "touchpoints/telegram-2/docker-compose.yml" --env-file "/data/eventwhisper/touchpoint-telegram.env" up -d --build